---
- hosts: dev
  become: yes
  tasks:
    - name: Set access time based on seconds from epoch value
      ansible.builtin.file:
        path: /etc/x
        state: touch
        access_time: '{{ "%Y%m%d%H%M.%S" | strftime }}'

