---
- hosts: dev
  become: yes
  tasks:
    - name: Update modification and access time of given file
      ansible.builtin.file:
        path: /work/x
        state: file
        modification_time: now
        access_time: now
